name: Docker Insaat Robotu

on: [push]  # Sen kod gönderince çalış

jobs:
  build-yapici:
    runs-on: ubuntu-latest  # Ubuntu sunucu kiraladık
    steps:
      - name: Malzemeleri Getir (Checkout)
        uses: actions/checkout@v3

      - name: Keki Pisir (Docker Build)
        run: docker build -t ismailin-otomatik-imaji .
      
      - name: Kanit Goster (Listele)
        run: docker images
